In [3]:
import pandas as pd
import os
from pathlib import Path
from google.colab import drive

# 1. Montar Google Drive
drive.mount('/content/drive')

# 2. Ruta del archivo TSV en Drive
# Cambiá esta ruta según dónde tengas guardado el archivo
archivo = "/content/drive/MyDrive/farmacos/Farmaco/TP FINAL/s001A.dali.tsv"

with open(archivo, "r", encoding="utf-8", errors="ignore") as f:
    lineas = f.readlines()

inicio_tabla = None

for i, linea in enumerate(lineas):
    # Una línea TSV real debería tener varias tabulaciones
    if linea.count("\t") >= 5:
        inicio_tabla = i
        break

if inicio_tabla is None:
    raise ValueError("No pude encontrar una tabla separada por tabulaciones en el archivo.")

print("La tabla parece empezar en la línea:", inicio_tabla + 1)

# Leer desde esa línea
df = pd.read_csv(
    archivo,
    sep="\t",
    skiprows=inicio_tabla,
    encoding="utf-8",
    engine="python"
)

df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
La tabla parece empezar en la línea: 6

,query,database,sbjct,z-score,rmsd,ali-length,sbjct-length,seq-identity,sbjct-sequence,compressed-sbjct-dssp,description,qstarts,sstarts,lengths,rotation,translation,all_pfam
0,s001A,PDB,7e8lA,26.0,0.0,119,119,100,VDEKYPSKYDNIDLDEILANKRLLTAYVNCIMERGKCSPEGKELKE...,10L9H1L11H7L16H6L17H1L11H4L12H5L8H1L,MOLECULE: PUTATIVE CHEMOSENSORY PROTEIN CSP8;,[1],[1],[119],"[1.0, -0.0, -0.0, 0.0, 1.0, -0.0, 0.0, 0.0, 1.0]","[0.0, 0.0, 0.0]","[['PF03392', 'PF03392', 5, 97, 2.6e-24, 93]]"
1,s001A,PDB,1kx9A,18.6,1.6,104,108,81,YTDKYDNINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQD...,1L14H1L11H7L16H6L17H1L11H4L12H7L,MOLECULE: CHEMOSENSORY PROTEIN A6;,[9],[5],[104],"[-0.805863, -0.535421, -0.2528, 0.587023, -0.7...","[2.738258, -1.079311, 17.410019]","[['PF03392', 'PF03392', 1, 93, 7.1e-25, 93]]"
2,s001A,PDB,1kx9B,18.5,1.4,100,102,80,INLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQDAIENGCK...,2L6H1L11H7L16H6L17H1L11H4L12H8L,MOLECULE: CHEMOSENSORY PROTEIN A6;,[13],[2],[100],"[-0.892402, -0.405756, -0.197434, 0.440108, -0...","[9.777532, 30.951803, 0.72096]","[['PF03392', 'PF03392', 1, 86, 7.2e-24, 93]]"
3,s001A,PDB,1kx8A,18.4,1.0,98,100,80,NINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQDAIENGC...,4L5H1L11H7L16H6L17H1L11H6L10H5L,MOLECULE: CHEMOSENSORY PROTEIN A6;,[13],[3],[98],"[0.847336, -0.113285, 0.518833, 0.411563, -0.4...","[-72.346947, 29.258423, -15.913952]","[['PF03392', 'PF03392', 1, 87, 2.3e-20, 93]]"
4,s001A,PDB,8xktA,13.7,1.9,90,93,44,NIDEIIENRKLLVPYIKCTLDQGRCTPEGRELKAHIKDAMQTSCSK...,1L6H1L11H7L15H7L17H1L11H6L8H2L,MOLECULE: CHEMOSENSORY PROTEIN;,[13 91 95],[ 1 81 86],[78 4 8],"[-0.30839, -0.263333, -0.914085, 0.898517, -0....","[11.566973, -9.688654, 14.995696]","[['PF03392', 'PF03392', 1, 85, 1.4e-20, 93]]"

In [4]:
# Limpiar nombres de columnas
df.columns = (
    df.columns
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
    .str.replace(".", "", regex=False)
)

print(df.columns)
df.head()

Index(['query', 'database', 'sbjct', 'z_score', 'rmsd', 'ali_length',
       'sbjct_length', 'seq_identity', 'sbjct_sequence',
       'compressed_sbjct_dssp', 'description', 'qstarts', 'sstarts', 'lengths',
       'rotation', 'translation', 'all_pfam'],
      dtype='object')

,query,database,sbjct,z_score,rmsd,ali_length,sbjct_length,seq_identity,sbjct_sequence,compressed_sbjct_dssp,description,qstarts,sstarts,lengths,rotation,translation,all_pfam
0,s001A,PDB,7e8lA,26.0,0.0,119,119,100,VDEKYPSKYDNIDLDEILANKRLLTAYVNCIMERGKCSPEGKELKE...,10L9H1L11H7L16H6L17H1L11H4L12H5L8H1L,MOLECULE: PUTATIVE CHEMOSENSORY PROTEIN CSP8;,[1],[1],[119],"[1.0, -0.0, -0.0, 0.0, 1.0, -0.0, 0.0, 0.0, 1.0]","[0.0, 0.0, 0.0]","[['PF03392', 'PF03392', 5, 97, 2.6e-24, 93]]"
1,s001A,PDB,1kx9A,18.6,1.6,104,108,81,YTDKYDNINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQD...,1L14H1L11H7L16H6L17H1L11H4L12H7L,MOLECULE: CHEMOSENSORY PROTEIN A6;,[9],[5],[104],"[-0.805863, -0.535421, -0.2528, 0.587023, -0.7...","[2.738258, -1.079311, 17.410019]","[['PF03392', 'PF03392', 1, 93, 7.1e-25, 93]]"
2,s001A,PDB,1kx9B,18.5,1.4,100,102,80,INLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQDAIENGCK...,2L6H1L11H7L16H6L17H1L11H4L12H8L,MOLECULE: CHEMOSENSORY PROTEIN A6;,[13],[2],[100],"[-0.892402, -0.405756, -0.197434, 0.440108, -0...","[9.777532, 30.951803, 0.72096]","[['PF03392', 'PF03392', 1, 86, 7.2e-24, 93]]"
3,s001A,PDB,1kx8A,18.4,1.0,98,100,80,NINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQDAIENGC...,4L5H1L11H7L16H6L17H1L11H6L10H5L,MOLECULE: CHEMOSENSORY PROTEIN A6;,[13],[3],[98],"[0.847336, -0.113285, 0.518833, 0.411563, -0.4...","[-72.346947, 29.258423, -15.913952]","[['PF03392', 'PF03392', 1, 87, 2.3e-20, 93]]"
4,s001A,PDB,8xktA,13.7,1.9,90,93,44,NIDEIIENRKLLVPYIKCTLDQGRCTPEGRELKAHIKDAMQTSCSK...,1L6H1L11H7L15H7L17H1L11H6L8H2L,MOLECULE: CHEMOSENSORY PROTEIN;,[13 91 95],[ 1 81 86],[78 4 8],"[-0.30839, -0.263333, -0.914085, 0.898517, -0....","[11.566973, -9.688654, 14.995696]","[['PF03392', 'PF03392', 1, 85, 1.4e-20, 93]]"

In [5]:
# Pasar a numérico
df["z_score"] = pd.to_numeric(df["z_score"], errors="coerce")
df["rmsd"] = pd.to_numeric(df["rmsd"], errors="coerce")
df["ali_length"] = pd.to_numeric(df["ali_length"], errors="coerce")

# Filtro estructural pedido por la consigna
df_filtrado = df[
    (df["z_score"] > 6) &
    (df["rmsd"] < 3.5) &
    (df["ali_length"] >= 50)
].copy()

# Filtro preliminar de humanos por descripción
"""df_filtrado["posible_humano"] = df_filtrado[desc_col].astype(str).str.contains(
    "human|homo sapiens",
    case=False,
    na=False
)"""

df_filtrado = df_filtrado.sort_values(
    by=["z_score", "ali_length"],
    ascending=[False, False]
)

df_filtrado.head(30)

,query,database,sbjct,z_score,rmsd,ali_length,sbjct_length,seq_identity,sbjct_sequence,compressed_sbjct_dssp,description,qstarts,sstarts,lengths,rotation,translation,all_pfam
0,s001A,PDB,7e8lA,26.0,0.0,119,119,100,VDEKYPSKYDNIDLDEILANKRLLTAYVNCIMERGKCSPEGKELKE...,10L9H1L11H7L16H6L17H1L11H4L12H5L8H1L,MOLECULE: PUTATIVE CHEMOSENSORY PROTEIN CSP8;,[1],[1],[119],"[1.0, -0.0, -0.0, 0.0, 1.0, -0.0, 0.0, 0.0, 1.0]","[0.0, 0.0, 0.0]","[['PF03392', 'PF03392', 5, 97, 2.6e-24, 93]]"
1,s001A,PDB,1kx9A,18.6,1.6,104,108,81,YTDKYDNINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQD...,1L14H1L11H7L16H6L17H1L11H4L12H7L,MOLECULE: CHEMOSENSORY PROTEIN A6;,[9],[5],[104],"[-0.805863, -0.535421, -0.2528, 0.587023, -0.7...","[2.738258, -1.079311, 17.410019]","[['PF03392', 'PF03392', 1, 93, 7.1e-25, 93]]"
2,s001A,PDB,1kx9B,18.5,1.4,100,102,80,INLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQDAIENGCK...,2L6H1L11H7L16H6L17H1L11H4L12H8L,MOLECULE: CHEMOSENSORY PROTEIN A6;,[13],[2],[100],"[-0.892402, -0.405756, -0.197434, 0.440108, -0...","[9.777532, 30.951803, 0.72096]","[['PF03392', 'PF03392', 1, 86, 7.2e-24, 93]]"
3,s001A,PDB,1kx8A,18.4,1.0,98,100,80,NINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQDAIENGC...,4L5H1L11H7L16H6L17H1L11H6L10H5L,MOLECULE: CHEMOSENSORY PROTEIN A6;,[13],[3],[98],"[0.847336, -0.113285, 0.518833, 0.411563, -0.4...","[-72.346947, 29.258423, -15.913952]","[['PF03392', 'PF03392', 1, 87, 2.3e-20, 93]]"
5,s001A,PDB,9j00B,13.7,2.0,98,107,41,YTTKYDGIDLDEILKSDRLFNNYFKCLMDEGRCTPDGNELKKILPE...,3L2E2L2E6H1L11H7L16H6L17H1L11H4L5H1L6H6L,MOLECULE: CHEMOSENSORY PROTEIN 3;,[10 14],[ 2 10],[ 4 94],"[-0.714064, -0.18797, 0.674374, 0.263595, -0.9...","[4.939771, -21.894903, 15.809484]","[['PF03392', 'PF03392', 1, 93, 1.5e-33, 93]]"
6,s001A,PDB,9iw4A,13.7,1.9,94,98,41,TTKYDGIDLDEILKSDRLFNNYFKCLMDEGRCTPDGNELKKILPEA...,2L2E2L2E6H1L11H7L16H6L17H1L11H4L5H5L,MOLECULE: CHEMOSENSORY PROTEIN 3;,[10 14],[1 9],[ 4 90],"[0.057623, 0.123455, 0.990676, -0.202276, 0.97...","[-19.495399, -14.973465, 38.993969]","[['PF03392', 'PF03392', 1, 92, 1.5e-28, 93]]"
4,s001A,PDB,8xktA,13.7,1.9,90,93,44,NIDEIIENRKLLVPYIKCTLDQGRCTPEGRELKAHIKDAMQTSCSK...,1L6H1L11H7L15H7L17H1L11H6L8H2L,MOLECULE: CHEMOSENSORY PROTEIN;,[13 91 95],[ 1 81 86],[78 4 8],"[-0.30839, -0.263333, -0.914085, 0.898517, -0....","[11.566973, -9.688654, 14.995696]","[['PF03392', 'PF03392', 1, 85, 1.4e-20, 93]]"
7,s001A,PDB,9j00A,13.6,2.2,92,94,42,TKYDGIDLDEILKSDRLFNNYFKCLMDEGRCTPDGNELKKILPEAL...,1L2E2L2E6H1L11H7L16H6L17H1L11H4L5H2L,MOLECULE: CHEMOSENSORY PROTEIN 3;,[ 9 13],[1 7],[ 4 88],"[0.798419, -0.147055, -0.583868, -0.274855, -0...","[-7.100458, 5.479, 40.081371]","[['PF03392', 'PF03392', 1, 91, 3.3e-28, 93]]"
8,s001A,PDB,9iw6B,13.4,2.0,90,92,42,TKYDGIDLDEILKSDRLFNNYFKCLMDEGRCTPDGNELKKILPEAL...,1L2E2L2E6H1L11H7L16H6L17H1L11H4L4H1L,MOLECULE: CHEMOSENSORY PROTEIN 3;,[ 9 13],[1 7],[ 4 86],"[0.175549, -0.587746, -0.78977, 0.943661, -0.1...","[25.131205, 6.617784, 33.672447]","[['PF03392', 'PF03392', 1, 91, 2.9e-32, 93]]"
10,s001A,PDB,9iw7A,13.3,2.4,94,97,41,VTKYDNIDLEEIFNSKRLMDNYMNCLKDVGPCTPDGRELKDNLPDA...,2L2E2L2E6H1L11H7L15H7L17H1L11H4L5H4L,MOLECULE: CHEMOSENSORY PROTEINS 3;,[ 8 12],[1 7],[ 4 90],"[0.054709, -0.749145, -0.660143, 0.950859, 0.2...","[19.809742, -14.724567, 16.605434]","[['PF03392', 'PF03392', 1, 92, 2.9e-23, 93]]"
9,s001A,PDB,9j01A,13.3,2.2,92,94,46,TKYDGIDLDEILKSDRLFNNYFKCLMDEGRCTPDGNELKKILPEAL...,1L2E2L2E5H2L11H7L16H6L17H1L11H4L5H2L,MOLECULE: CHEMOSENSORY PROTEIN 3;,[9],[3],[92],"[-0.539978, -0.127197, 0.832012, 0.221387, -0....","[1.651807, 0.305889, 26.412273]","[['PF03392', 'PF03392', 1, 91, 3.3e-28, 93]]"
11,s001A,PDB,9j00C,13.2,2.2,96,101,41,YTTKYDGIDLDEILKSDRLFNNYFKCLMDEGRCTPDGNELKKILPE...,3L2E2L2E6H1L11H7L16H6L17H1L11H4L5H1L5H1L,MOLECULE: CHEMOSENSORY PROTEIN 3;,[10 14],[ 2 10],[ 4 92],"[-0.29675, -0.149172, 0.943232, 0.308408, -0.9...","[-22.436728, -32.019283, -29.434072]","[['PF03392', 'PF03392', 1, 93, 1.1e-28, 93]]"
12,s001A,PDB,1n8vA,12.9,2.0,96,101,76,KYTDKYDNINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQ...,10L5H2L11H7L16H6L17H1L11H6L8H1L,MOLECULE: CHEMOSENSORY PROTEIN;,[ 8 14],[ 6 11],[ 5 91],"[0.498144, 0.737513, -0.45599, -0.749307, 0.63...","[-16.24238, -10.782241, -15.890553]","[['PF03392', 'PF03392', 2, 94, 5.6e-25, 93]]"
13,s001A,PDB,1n8vB,12.9,2.0,96,103,76,EDKYTDKYDNINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEH...,12L6H1L11H7L16H6L17H1L11H6L8H1L,MOLECULE: CHEMOSENSORY PROTEIN;,[ 8 13],[ 8 12],[ 4 92],"[-0.499731, 0.683189, 0.532468, 0.746349, 0.65...","[-21.493492, -17.452095, 11.397317]","[['PF03392', 'PF03392', 4, 96, 5.9e-29, 93]]"
15,s001A,PDB,1n8uA,12.7,2.0,95,100,77,KYTDKYDNINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEHLQ...,10L6H1L11H7L16H6L17H1L11H6L7H1L,MOLECULE: CHEMOSENSORY PROTEIN;,[ 8 13],[ 6 10],[ 4 91],"[-0.224645, 0.708509, -0.668991, -0.192716, 0....","[0.64946, 3.6679, 5.668121]","[['PF03392', 'PF03392', 2, 94, 5.5e-25, 93]]"
16,s001A,PDB,9iw8A,12.7,2.6,94,96,41,VTKYDNIDLEEIFNSKRLMDNYMNCLKDVGPCTPDGRELKDNLPDA...,2L2E2L2E5H2L11H7L16H6L17H1L11H4L6H2L,MOLECULE: CHEMOSENSORY PROTEINS 3 FROM ANOPHEL...,[ 8 12],[1 7],[ 4 90],"[0.300099, -0.577189, -0.75947, -0.509074, 0.5...","[-29.373583, -4.37997, 34.41626]","[['PF03392', 'PF03392', 1, 92, 2.8e-23, 93]]"
14,s001A,PDB,9iw6A,12.7,1.8,90,99,42,MQEQYTTKYDGIDLDEILKSDRLFNNYFKCLMDEGRCTPDGNELKK...,7L2E2L2E6H1L11H7L16H6L17H1L11H4L5H1L,MOLECULE: CHEMOSENSORY PROTEIN 3;,[10 14],[ 6 14],[ 4 86],"[0.169034, 0.693854, 0.699996, 0.962594, 0.036...","[-23.447599, -6.948325, 23.775568]","[['PF03392', 'PF03392', 5, 97, 1.2e-29, 93]]"
17,s001A,PDB,9iw5A,12.6,1.8,90,99,42,QEQYTTKYDGIDLDEILKSDRLFNNYFKCLMDEGRCTPDGNELKKI...,6L2E2L2E6H1L11H7L15H7L17H1L11H4L6H1L,MOLECULE: CHEMOSENSORY PROTEIN 3;,[10 14],[ 5 13],[ 4 86],"[0.153417, 0.7426, -0.651927, 0.957193, -0.275...","[-12.229291, -13.914278, 40.502342]","[['PF03392', 'PF03392', 4, 96, 1.2e-29, 93]]"
18,s001A,PDB,2gvsA,10.1,3.0,95,109,45,EEKYTTKYDNVNLDEILANDRLLNKYVQCLLEDDESNCTADGKELK...,12L6H1L12H10L7H2L4H7L17H1L11H7L4H8L,MOLECULE: CHEMOSENSORY PROTEIN CSP-SG4;,[ 12 32 36 108],[ 11 30 37 103],[19 4 66 6],"[-0.967249, -0.184874, -0.17393, 0.000733, 0.6...","[-5.856874, 3.503633, 20.336525]","[['PF03392', 'PF03392', 4, 98, 8.6e-27, 93]]"
19,s001A,PDB,2jntA,8.0,3.1,99,108,52,YTDKYDKINLQEILENKRLLESYMDCVLGKGKCTPEGKELKDHLQE...,10L4H2L11H7L14H8L16H2L11H6L11H6L,MOLECULE: CHEMOSENSORY PROTEIN CSP1;,[13 39 59],[ 9 36 55],[26 19 54],"[-0.172419, 0.906136, 0.38625, 0.515063, 0.417...","[-6.057682, 3.923388, 19.149319]","[['PF03392', 'PF03392', 1, 93, 2.2e-24, 93]]"
20,s001A,PDB,1k19A,7.1,3.4,90,112,64,EDKYTDKYDNINLDEILANKRLLVAYVNCVMERGKCSPEGKELKEH...,12L5H2L11H6L14H10L17H2L7H8L11H7L,MOLECULE: CHEMOSENSORY PROTEIN CSP2;,[ 13 35 41 54 60 81 88 107],[ 12 36 40 52 59 79 87 105],[22 4 10 5 20 7 18 4],"[-0.349568, -0.893476, -0.281962, 0.923158, -0...","[-5.383733, 3.318511, 18.479452]","[['PF03392', 'PF03392', 4, 96, 8e-25, 93]]"

In [6]:
salida = "/content/drive/MyDrive/farmacos/Farmaco/TP FINAL/dali_candidatos_filtrados.csv"

df_filtrado.to_csv(salida, index=False)

print("Archivo guardado en:", salida)

Archivo guardado en: /content/drive/MyDrive/farmacos/Farmaco/TP FINAL/dali_candidatos_filtrados.csv